spring:
  profiles:
    active: local
    group:
      local:
        - common
      test:
        - common

---
spring:
  config.activate.on-profile: common
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
jwt:
  token:
    secret-key: ${TOKEN_SECRET_KEY}
    access-expired-ms: ${TOKEN_ACCESS_EXPIRED_MS}

---
spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    defer-datasource-initialization: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  devtools.livereload:
    enabled: true
    port: 35730

---
spring:
  config.activate.on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    defer-datasource-initialization: true
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:init.sql'
