spring:
  config.activate.on-profile: common
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
local-file:
  relative-path: ${LOCAL_FILE_REL_PATH}
  absolute-path: ${LOCAL_FILE_ABS_PATH}
aws.s3:
  bucket-name: ${S3_BUCKET_NAME}
  url: ${S3_URL}
async.executor:
  core-pool-size: ${CORE_POOL_SIZE}
  max-pool-size: ${MAX_POOL_SIZE}
  queue-capacity: ${QUEUE_CAPACITY}
  thread-name-prefix: ${THREAD_NAME_PREFIX}
