spring:
  profiles:
    active: local
    group:
      local:
        - common
        - mail
      test:
        - common
        - mail

---
spring:
  config.activate.on-profile: common
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
jwt:
  token:
    secret-key: ${TOKEN_SECRET_KEY}
    access-expired-ms: ${TOKEN_ACCESS_EXPIRED_MS}
local-file:
  relative-path: ${LOCAL_FILE_REL_PATH}
  absolute-path: ${LOCAL_FILE_ABS_PATH}
async.executor:
  core-pool-size: ${CORE_POOL_SIZE}
  max-pool-size: ${MAX_POOL_SIZE}
  queue-capacity: ${QUEUE_CAPACITY}
  thread-name-prefix: ${THREAD_NAME_PREFIX}

---
spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  devtools.livereload:
    enabled: true
    port: 35730

---
logging:
  level:
    org.springframework: debug
spring:
  config.activate.on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    defer-datasource-initialization: true
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:init.sql'
