spring:
  profiles:
    active: local # default
    group:
      local:
        - common
        - security
        - mail
      prod:
        - common
        - security
        - mail
      test:
        - security
        - mail

---
spring:
  config.activate.on-profile: local
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  devtools.livereload:
    enabled: true
    port: 35730

---
logging:
  level:
    org.springframework: debug
spring:
  config.activate.on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    defer-datasource-initialization: true
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=RUNSCRIPT FROM 'classpath:init.sql'

---
spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: false
