spring:
  config.activate.on-profile: common
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
async.executor:
  core-pool-size: ${CORE_POOL_SIZE}
  max-pool-size: ${MAX_POOL_SIZE}
  queue-capacity: ${QUEUE_CAPACITY}
  thread-name-prefix: ${THREAD_NAME_PREFIX}
